### ISSUE TITLE
Is there any way to change the download file name?

### ISSUE THREAD

**Issue by tangshuang** [hongru/canvas2image#19]
I know, a tag has a `download` attr, but not expected browsers support this. 
I checked the source and found @hongru uses `location.href=data` to download, which makes the file name only be 'download'.

So, is there any way to change the name?

**Comment by vitek499** [comment]
```
var ctx = document.getElementById("myChart");
var link = document.createElement("a");
link.download = "filename.png";
link.href = Canvas2Image.convertToPNG(ctx, ctx.width(), ctx.height()).src;
link.click();
```

**Comment by tangshuang** [comment]
@vitek499 I have mentioned `download` attr is not expected.
I just found a pacakge called `downloadjs` which can easily touch my demand.
