### ISSUE TITLE
download name

### ISSUE THREAD

**Issue by gcalex5** [hongru/canvas2image#3]
I'm seeing that when I do a save as it isn't setting a name or file extension. However I can still open the file as and image.

**Comment by renatosc** [comment]
Same question here. How do I specify the name of the file to be saved?

**Comment by joeyespo** [comment]
Looks like it's not built into this particular library, but here's [how to do it in general](http://stackoverflow.com/questions/283956/is-there-any-way-to-specify-a-suggested-filename-when-using-data-uri).

**Comment by chitru** [comment]
As given by @ivansnek it worked for me it may help you too...
var dataString = canvas.toDataURL("image/png");
var link = document.createElement("a");
link.download = 'image';
link.href = dataString;
link.click();

**Comment by polidashow** [comment]
I had the same issue so i change a little bit of the Canvas2image.js. Here's what i did:

- When it generates the image link for download, the script replaces the 'type' var to 'data/<MY_TYPE>', So, on the SaveAsImage function, i did this:
`var saveAsImage = function (canvas, width, height, type) {
		if ($support.canvas && $support.dataURL) {
			if (typeof canvas == "string") { canvas = document.getElementById(canvas); }
			if (type == undefined) { type = 'png'; }
			var fileExt = type; // Here, i get the file extension by the type var
			type = fixType(type);
			if (/bmp/.test(type)) {
				var data = getImageData(scaleCanvas(canvas, width, height));
				var strData = genBitmapImage(data);
				saveFile(makeURI(strData, downloadMime),fileExt); // Then here, pass a new parameter with the file extension. You will understand why on the next Step
			} else {
				var strData = getDataURL(canvas, type, width, height);
				saveFile(strData.replace(type, downloadMime),fileExt); // Same thing here (new parameter)
			}
		}
	};`

Once i passed the fileExtension variable, it saves the file changing the document.location.href, and there is the problem. You specificate what kind of extension you want, but the computer doesn't get it. So, i changed the SaveFile function in a very rustic way:

`function saveFile (strData, type) {
		var link = document.createElement('a');
    link.download = '<YOUR_FILE_NAME>.'+type;
    link.href = strData;
    link.click();
	}`

Not tested in Firefox, but i thint that works

**Comment by ChetnaGupta** [comment]
@polidashow I know its too late but does this solution works in IE11 ? I am kinda not able to see anything happening in IE11 after adding this piece of code.

**Comment by polidashow** [comment]
@ChetnaGupta it doesn't work, unfortunately, because IE11 doesn't support the "download" feature, as explained [here](https://stackoverflow.com/a/18408028). What i would do is convert the `strData` to a 
base64 string, open a new window with the base64 string and let the user do the download action. However i don't think it will work, since i don't have acknowledge on using IE11 for development. Let me know if you find an possible solution for it.

**Comment by sukhchainn** [comment]
In which folder is it saving the file? I can't find it.
