### ISSUE TITLE
Image Downloads But FormatLess

### ISSUE THREAD

**Issue by Kavian77** [hongru/canvas2image#8]
What is Wrong ?
all things are well but the images that is downloaded , is formatless and image viewers cant open them .
in your demo this problem exists too .
can you please solve this ?

**Comment by ivansnek** [comment]
Hi  I had the same problem and I couldn't solve it, but finally I came across with this solution, hope it helps: 
`var dataString = canvas.toDataURL("image/png");`
`var link = document.createElement("a");`
`link.download = 'image';`
`link.href = dataString;`
`link.click();`

**Comment by xoorath** [comment]
I also have this problem, but @ivansnek 's solution doesn't work for me. The image comes out completely black.

**Comment by broven** [comment]
I fixed that. just use it in my fork repo.
